"""Writes the app icon drawables from icon_concepts.py. Run from the repo root:

    python3 design/icon/make_icon.py

Outputs the adaptive icon layers, the themed-icon (monochrome) layer, the status-bar
notification icon, the in-app logo, and an SVG preview of the full-colour icon.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from icon_concepts import CONCEPTS, rrect, to_svg, to_vector_drawable  # noqa: E402

SHIPPED = "ink"
RES = "app/src/main/res/drawable"
SRC = "Generated by design/icon/make_icon.py; edit that, not this file."

layers = CONCEPTS[SHIPPED]()


def write(path, text):
    with open(path, "w") as f:
        f.write(text)
    print("wrote", path)


write(f"{RES}/ic_launcher_background.xml", to_vector_drawable(layers["bg"], SRC))
write(f"{RES}/ic_launcher_foreground.xml", to_vector_drawable(layers["fg"], SRC))
write(f"{RES}/ic_launcher_monochrome.xml", to_vector_drawable(layers["mono"], SRC))

# Status-bar icon: the monochrome glyph, white, cropped to the 52-unit square around
# the centre of the 108 canvas and drawn at 24dp (strokes come out at about 2dp).
mono = to_vector_drawable(layers["mono"], SRC).replace("#FF000000", "#FFFFFFFF")
mono = mono.replace('android:width="108dp" android:height="108dp"\n    android:viewportWidth="108" android:viewportHeight="108">',
                    'android:width="24dp" android:height="24dp"\n    android:viewportWidth="52" android:viewportHeight="52">\n'
                    '    <group android:translateX="-28" android:translateY="-28">')
mono = mono.replace("</vector>", "    </group>\n</vector>")
write(f"{RES}/ic_notification.xml", mono)

# In-app logo: the full-colour icon as a rounded square, drawn at 24dp by default.
logo = to_vector_drawable(layers["bg"] + layers["fg"], SRC)
logo = logo.replace('android:width="108dp" android:height="108dp"\n    android:viewportWidth="108" android:viewportHeight="108">',
                    'android:width="24dp" android:height="24dp"\n    android:viewportWidth="72" android:viewportHeight="72">\n'
                    '    <group android:translateX="-18" android:translateY="-18">\n'
                    f'        <clip-path android:pathData="{rrect(18, 18, 72, 72, 17).d()}" />')
logo = logo.replace("</vector>", "    </group>\n</vector>")
write(f"{RES}/ic_logo.xml", logo)

d1, b1 = to_svg(layers["bg"], "b")
d2, b2 = to_svg(layers["fg"], "f")
write("design/icon/ink-wave.svg",
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="512" height="512">'
      f'<defs><clipPath id="m"><circle cx="54" cy="54" r="36"/></clipPath>{d1}{d2}</defs>'
      f'<g clip-path="url(#m)">{b1}{b2}</g></svg>\n')
